"use client";
import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faGear,
  faSliders,
  faCircleInfo,
  faComments,
  faScrewdriverWrench,
  faScroll,
  faDatabase,
  faStar,
  faXmark,
  faBars,
  faThumbsUp,
  faThumbsDown,
  faMinus,
  faPlus,
  faUpRightAndDownLeftFromCenter,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faRotateRight,
  faPalette,
  faCopy,
  faCheck,
  faSquare,
  faTrash,
  faPenToSquare,
  faSearch,
  faEye,
  faFolderOpen,
  faSave,
  faCodeCompare,
} from "@fortawesome/free-solid-svg-icons";

const icons = {
  gear: faGear,
  sliders: faSliders,
  info: faCircleInfo,
  comments: faComments,
  tools: faScrewdriverWrench,
  scroll: faScroll,
  db: faDatabase,
  star: faStar,
  close: faXmark,
  bars: faBars,
  thumbsUp: faThumbsUp,
  thumbsDown: faThumbsDown,
  minus: faMinus,
  plus: faPlus,
  expand: faUpRightAndDownLeftFromCenter,
  chevronDown: faChevronDown,
  "chevron-down": faChevronDown,
  "chevron-left": faChevronLeft,
  "chevron-right": faChevronRight,
  refresh: faRotateRight,
  palette: faPalette,
  copy: faCopy,
  check: faCheck,
  stop: faSquare,
  trash: faTrash,
  edit: faPenToSquare,
  search: faSearch,
  eye: faEye,
  "folder-open": faFolderOpen,
  save: faSave,
  "git-compare": faCodeCompare,
} as const;

export type _IconNameForceInclude = 'edit';
export type IconName = _IconNameForceInclude | keyof typeof icons;
export const Icon: React.FC<{ name: IconName; className?: string; title?: string; style?: React.CSSProperties }> = ({ name, className, title, style }) => (
  <FontAwesomeIcon icon={icons[name]} className={className} title={title} style={style} />
);
